### ISSUE TITLE
Basic window manipulation

### ISSUE THREAD

**Issue by sigmasoldi3r** [oscurojs/oscurojs-node-lib#4]
Implement basic window manipulation:
- Resize command `RESIZEWIN` (plus width and height)
- Set title command `SETWINTITLE` (plus base64 title)

**Comment by Adria1993** [comment]
Entiendo que esta parte va en el app js no?, que es otro metodo del socket.

**Comment by sigmasoldi3r** [comment]
no, va a window Window

**Comment by sigmasoldi3r** [comment]
closing until protocol is defined
